### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by diegomartinezdesantiago** [pschocke/laravel-telegram-login-widget#6]
when i ran,
$ php artisan vendor:publish --tag=telegramloginwidget

there is error message like this :
"Unable to locate publishable resources.
Publishing complete."

my laravel version is: 7.10.03

**Comment by pschocke** [comment]
Hey, sorry for that inconvenience, the command should be
`php artisan vendor:publish --tag=telegramloginwidget.config`

I'll update the readme, thanks for pointing this out!

**Comment by diegomartinezdesantiago** [comment]
Ok, thanks.
